# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rcqrs-rails"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Smith"]
  s.date = "2012-03-01"
  s.email = "ben@slashdotdash.net"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "example/event_storage.yml",
    "lib/generators/rcqrs/command/command_generator.rb",
    "lib/generators/rcqrs/command/templates/command.rb",
    "lib/generators/rcqrs/command/templates/handler.rb",
    "lib/generators/rcqrs/domain/domain_generator.rb",
    "lib/generators/rcqrs/domain/templates/domain.rb",
    "lib/generators/rcqrs/event/event_generator.rb",
    "lib/generators/rcqrs/event/templates/event.rb",
    "lib/generators/rcqrs/event/templates/handler.rb",
    "lib/generators/rcqrs/install/install_generator.rb",
    "lib/rcqrs-rails.rb",
    "lib/rcqrs/gateway.rb",
    "lib/rcqrs/setting.rb",
    "rcqrs-rails.gemspec"
  ]
  s.homepage = "http://github.com/slashdotdash/rcqrs-rails"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Rails 3 plugin to use the RCQRS library"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rcqrs>, [">= 0"])
    else
      s.add_dependency(%q<rcqrs>, [">= 0"])
    end
  else
    s.add_dependency(%q<rcqrs>, [">= 0"])
  end
end

